### ISSUE TITLE
 add heat support to openstack-utils

### ISSUE THREAD

**Issue by asalkeld** [redhat-openstack/openstack-utils#15]
We have had this bug in the heat lp for ages, I think it belongs here rather.
lp bug: https://bugs.launchpad.net/heat/+bug/1154139

**Comment by apevec** [comment]
Copying from LP bug, request was to add setup-heat-db script  to https://github.com/redhat-openstack/openstack-utils/blob/master/utils/openstack-db

Instead, openstack-db should be removed, it's out of date.
