### ISSUE TITLE
openstack-db is out of date

### ISSUE THREAD

**Issue by apevec** [redhat-openstack/openstack-utils#19]
Instead of trying to reimplement openstack puppet or similar in bash, let's remove it instead,
like openstack-demo-install was removed in https://github.com/redhat-openstack/openstack-utils/commit/77a7fa859cf78eaef4e7d1b03b5a21d1e76bcc6e

**Comment by apevec** [comment]
@hguemar I propose this as a blocker for 2016.1 release

**Comment by hguemar** [comment]
:+1:
